"""Initial migration

Revision ID: 972f6c9fdbaa
Revises: 
Create Date: 2025-03-24 23:53:23.651257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972f6c9fdbaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    # ### end Alembic commands ###
